# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20160409_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerexpression',
            name='data_calc_args',
            field=models.CharField(default=1, help_text='\u82e5\u662f\u591a\u4e2a\u53c2\u6570,\u5219\u7528,\u53f7\u5206\u5f00,\u7b2c\u4e00\u4e2a\u503c\u662f\u65f6\u95f4', max_length=64, verbose_name='\u51fd\u6570\u4f20\u5165\u53c2\u6570'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triggerexpression',
            name='data_calc_func',
            field=models.CharField(choices=[(b'avg', b'Average'), (b'max', b'Max'), (b'hit', b'Hit'), (b'last', b'Last')], default=1, max_length=64, verbose_name='\u6570\u636e\u5904\u7406\u65b9\u5f0f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='left_sibling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_sibling_condition', to='monitor.TriggerExpression', verbose_name='\u5de6\u8fb9\u6761\u4ef6'),
        ),
    ]
