# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20160425_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='expressions',
        ),
        migrations.RemoveField(
            model_name='triggerexpression',
            name='name',
        ),
        migrations.RemoveField(
            model_name='triggerexpression',
            name='next_condition',
        ),
        migrations.AddField(
            model_name='triggerexpression',
            name='trigger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor.Trigger', verbose_name='\u6240\u5c5e\u89e6\u53d1\u5668'),
            preserve_default=False,
        ),
    ]
