# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20160425_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerexpression',
            name='specified_index_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53ea\u76d1\u63a7\u4e13\u95e8\u6307\u5b9a\u7684\u6307\u6807key'),
        ),
    ]
