# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_triggerexpression_specified_index_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_sub_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='logic_type',
            field=models.CharField(blank=True, choices=[(b'or', b'OR'), (b'and', b'AND')], max_length=32, null=True, verbose_name='\u4e0e\u4e00\u4e2a\u6761\u4ef6\u7684\u903b\u8f91\u5173\u7cfb'),
        ),
    ]
