# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20160519_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='has_sub_service',
            field=models.BooleanField(default=False, help_text='\u5982\u679c\u4e00\u4e2a\u670d\u52a1\u8fd8\u6709\u72ec\u7acb\u7684\u5b50\u670d\u52a1 ,\u9009\u62e9\u8fd9\u4e2a,\u6bd4\u5982 \u7f51\u5361\u670d\u52a1\u6709\u591a\u4e2a\u72ec\u7acb\u7684\u5b50\u7f51\u5361'),
        ),
    ]
