# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20160524_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncondtion',
            name='severity',
            field=models.IntegerField(choices=[(1, b'Information'), (2, b'Warning'), (3, b'Average'), (4, b'High'), (5, b'Diaster')], default=1, verbose_name='\u6240\u8fbe\u5230\u7684\u544a\u8b66\u7ea7\u522b'),
            preserve_default=False,
        ),
    ]
