# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_actioncondtion_severity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actioncondtion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='actioncondtion',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actioncondtion',
            name='trigger',
        ),
        migrations.DeleteModel(
            name='ActionCondtion',
        ),
    ]
