# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_remove_actioncondtion_severity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actioncondtion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='actioncondtion',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actioncondtion',
            name='trigger',
        ),
        migrations.AddField(
            model_name='action',
            name='triggers',
            field=models.ManyToManyField(blank=True, help_text='\u60f3\u8ba9\u54ea\u4e9btrigger\u89e6\u53d1\u5f53\u524d\u62a5\u8b66\u52a8\u4f5c', to='monitor.Trigger'),
        ),
        migrations.DeleteModel(
            name='ActionCondtion',
        ),
    ]
