# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_host_host_alive_check_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.IntegerField(choices=[(1, b'Online'), (2, b'Down'), (3, b'Unreachable'), (4, b'Offline'), (5, b'Problem')], default=1, verbose_name='\u72b6\u6001'),
        ),
    ]
